# Generated by Django 3.1.4 on 2020-12-09 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('jobTitle', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=10)),
                ('website', models.CharField(max_length=150)),
                ('aadharNo', models.CharField(max_length=12)),
                ('experience', models.CharField(max_length=3)),
                ('mobile', models.BigIntegerField()),
                ('email', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('intro', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proName', models.CharField(blank=True, max_length=500, null=True)),
                ('proService', models.CharField(blank=True, max_length=500, null=True)),
                ('proInfo', models.CharField(blank=True, max_length=500, null=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('span', models.CharField(blank=True, max_length=10, null=True)),
                ('role', models.CharField(blank=True, max_length=200, null=True)),
                ('agency', models.CharField(blank=True, max_length=500, null=True)),
                ('workedOn', models.CharField(blank=True, max_length=500, null=True)),
                ('workPerformed', models.CharField(blank=True, max_length=500, null=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Coding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=500, null=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('span10', models.CharField(blank=True, max_length=10, null=True)),
                ('university10', models.CharField(blank=True, max_length=200, null=True)),
                ('school10', models.CharField(blank=True, max_length=500, null=True)),
                ('percent10', models.FloatField()),
                ('span12', models.CharField(blank=True, max_length=10, null=True)),
                ('university12', models.CharField(blank=True, max_length=200, null=True)),
                ('college12', models.CharField(blank=True, max_length=500, null=True)),
                ('percent12', models.FloatField()),
                ('spanGrad', models.CharField(blank=True, max_length=10, null=True)),
                ('courseGrad', models.CharField(blank=True, max_length=200, null=True)),
                ('schoolGrad', models.CharField(blank=True, max_length=500, null=True)),
                ('percentGrad', models.FloatField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.personalinfo')),
            ],
        ),
    ]
