# Generated by Django 3.1.4 on 2020-12-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='username',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
