# Generated by Django 3.1.4 on 2020-12-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_personalinfo_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='aadharNo',
            field=models.CharField(max_length=20),
        ),
    ]
