# Generated by Django 3.1.4 on 2020-12-18 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_auto_20201209_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('compName', models.CharField(max_length=200)),
                ('jobTitle', models.CharField(max_length=200)),
                ('scores', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.personalinfo')),
            ],
        ),
    ]
