# Generated by Django 3.1.4 on 2021-02-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='course',
            field=models.CharField(default='CE', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selection',
            name='fullname',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selection',
            name='grad',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selection',
            name='hsc',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selection',
            name='salary',
            field=models.BigIntegerField(default=230000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selection',
            name='ssc',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
