# Generated by Django 3.1.4 on 2021-03-01 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_auto_20210227_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selection2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=200)),
                ('ssc', models.CharField(max_length=10)),
                ('hsc', models.CharField(max_length=10)),
                ('grad', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=300)),
                ('scores', models.IntegerField()),
                ('compName', models.CharField(max_length=200)),
                ('salary', models.BigIntegerField()),
                ('jobTitle', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.personalinfo')),
            ],
        ),
    ]
