# Generated by Django 3.1.4 on 2021-03-02 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_selection2'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackerRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rankName', models.CharField(blank=True, max_length=500, null=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.personalinfo')),
            ],
        ),
    ]
