# Generated by Django 3.1.4 on 2021-03-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_hackerrank'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackerrank',
            name='courses',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hackerrank',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
