# Generated by Django 3.1.4 on 2020-12-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='percentGrad',
            field=models.FloatField(default=70),
            preserve_default=False,
        ),
    ]
