# Generated by Django 3.1.4 on 2020-12-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_register_percentgrad'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedBeforeTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('candidateID', models.BigIntegerField()),
                ('candidateName', models.CharField(max_length=200)),
                ('percent10', models.FloatField()),
                ('percent12', models.FloatField()),
                ('percentGrad', models.FloatField()),
                ('exp', models.CharField(max_length=3)),
            ],
        ),
    ]
