# Generated by Django 3.1.4 on 2020-12-15 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0003_selectedbeforetest'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedbeforetest',
            name='uid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recruiter.register'),
            preserve_default=False,
        ),
    ]
