# Generated by Django 3.1.4 on 2020-12-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0004_selectedbeforetest_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedbeforetest',
            name='status',
            field=models.CharField(default='Selected', max_length=20),
            preserve_default=False,
        ),
    ]
