# Generated by Django 3.1.4 on 2020-12-15 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0005_selectedbeforetest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedbeforetest',
            name='status',
        ),
        migrations.CreateModel(
            name='Registered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('candidateID', models.BigIntegerField()),
                ('candidateName', models.CharField(max_length=200)),
                ('percent10', models.FloatField()),
                ('percent12', models.FloatField()),
                ('percentGrad', models.FloatField()),
                ('exp', models.CharField(max_length=3)),
                ('status', models.CharField(max_length=20)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.register')),
            ],
        ),
    ]
