# Generated by Django 3.1.4 on 2020-12-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0006_auto_20201216_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('question', models.CharField(max_length=2000)),
                ('qa', models.CharField(max_length=2000)),
                ('qb', models.CharField(max_length=2000)),
                ('qc', models.CharField(max_length=2000)),
                ('qd', models.CharField(max_length=2000)),
                ('qAns', models.CharField(max_length=2000)),
            ],
        ),
    ]
