# Generated by Django 3.1.4 on 2020-12-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0007_testquestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('canID', models.BigIntegerField()),
                ('canUser', models.CharField(max_length=200)),
                ('scores', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
