# Generated by Django 3.1.4 on 2021-02-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0008_testscores'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehavioralQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=2000)),
                ('qa', models.CharField(max_length=2000)),
                ('qb', models.CharField(max_length=2000)),
                ('qc', models.CharField(max_length=2000)),
                ('qd', models.CharField(max_length=2000)),
                ('qAns', models.CharField(max_length=2000)),
            ],
        ),
    ]
