# Generated by Django 3.1.4 on 2021-02-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0009_behavioralquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='behavioralquestions',
            name='qe',
            field=models.CharField(default='abc', max_length=2000),
            preserve_default=False,
        ),
    ]
