# Generated by Django 3.1.4 on 2021-03-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0010_behavioralquestions_qe'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestScores2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('canID', models.BigIntegerField()),
                ('canUser', models.CharField(max_length=200)),
                ('scores', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
