# Generated by Django 3.1.4 on 2021-03-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0011_testscores2'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='max',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
